services:
  db:
    image: postgres
    container_name: books_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  bookapp:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      DB_HOST: db
      db_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: books